/**
 * WebSocket Chat Constants
 */

export const DEFAULT_WS_PATH = '/ws/chat/view';
export const ALT_WS_PATH = '/ws/chat-view';

export const DEFAULT_HEARTBEAT_INTERVAL_SEC = 25;
export const DEFAULT_HEARTBEAT_TIMEOUT_SEC = 75;

export const WS_CLOSE_CODE_NORMAL = 1000;
export const WS_CLOSE_CODE_DUPLICATE_SESSION = 4001;

export const WS_ERROR_CODES = {
  MESSAGE_TYPE_REQUIRED: 'MESSAGE_TYPE_REQUIRED',
  UNKNOWN_MESSAGE_TYPE: 'UNKNOWN_MESSAGE_TYPE',
  INVALID_JSON: 'INVALID_JSON',
  INVALID_MESSAGE_SIZE: 'INVALID_MESSAGE_SIZE',
  MESSAGE_TOO_LARGE_OR_FRAGMENTED: 'MESSAGE_TOO_LARGE_OR_FRAGMENTED',
  ROOM_ID_REQUIRED: 'ROOM_ID_REQUIRED',
  NOT_ROOM_MEMBER: 'NOT_ROOM_MEMBER',
  NO_ACTIVE_ROOM: 'NO_ACTIVE_ROOM',
  MESSAGE_ID_REQUIRED: 'MESSAGE_ID_REQUIRED',
  MESSAGE_NOT_FOUND_OR_INVALID: 'MESSAGE_NOT_FOUND_OR_INVALID',
  ROOM_MISMATCH: 'ROOM_MISMATCH',
} as const;
